### ISSUE TITLE
Add ability to attach data to requests

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/scala-debugger#22]
It looks like you can attach data to requests via the `putProperty(key, value)` method of the JDI Request class. I'm making the assumption that this data can then be retrieved via `getProperty(key)` from the JDI Request if you access it from the resulting event via `Event.request().getProperty(key)`.

This needs investigation, but if this is the case, this opens up the floodgates for much more accurate listening for events corresponding to specific requests. Performing something like "give me a future for the next event matching this request" suddenly becomes a lot more doable.

If this works, need to figure out how to 1) use the case class pattern to feed in properties 2) use the data request pattern (for pulling out information) to get property values from events.

If it is done right, should be able to use that functionality to write the abstraction for the `runOnceHandler(...)` idea.

**Comment by rorygraves** [comment]
I hope this works as suggested, that sounds awesome

**Comment by chipsenkbeil** [comment]
@rorygraves, just did a brief test of this by adding a property "key" = s"$fileName:$lineNumber" in the breakpoint manager and pulling out the "key" property within the breakpoint manager integration tests. Looks like it works as expected in terms of accessing the property from the event's request, which is great news! :)

**Comment by chipsenkbeil** [comment]
Filters branch now contains a few property case classes and processors including `CustomProperty(key: AnyRef, value: AnyRef)`, which will be applied to `EventRequest.putProperty(key, value)`.

At the low level, it will still be up to the developer to pull out the property from the event when the event handler fires, but extracting property data in a higher level might fit in the same vein as #9.
